### PR TITLE
Add "Exfiltrate data via the logs of GCP Org policy"

### PR DESCRIPTION
**Pull request by jon-trust**

### CODE REVIEW

**Comment by jon-trust** [comment]
Resolved conflict and updated style.

**Comment by jon-trust** [comment]
Any updates?

**Comment by 0xdabbad00** [comment]
This is going to open a can of worms as AWS has a lot of similar issues, where if we make an assumption about an isolated environment and attacker controlled code runs in it, there are ways to exfil out data, and I fear there are a lot of these that we should classify this bug class somehow.

**Comment by jon-trust** [comment]
Thanks for merging. Some more context: data exfil/leakage vector is one of the big concerns for some of our customers, and should be fixed by CSPs. Fun fact: VPC endpoints do not generate CloudTrail on deny events for that very reason.

**Pull request merged**
